# English Premier League (EPL) Pythagorean Predictor

Load the datafile (this contains 6 variables: the date, home team, away team, goals scored (FTHG), goals against (FTAG) andthe result (H- home win, D- draw, A â€“ away win).

Create a value for a home wins (win= 1, draw=0.5, loss= 0) and away wins and a count variable for each game (=1).

Create a file for games played in 2017 (before date 20180000) and another one for games played in 2018 (after date 20180000).
For the 2017 games, use .groupby to create a dataframe aggregating by home team the variables for count, home wins, goals for and goals against.  Then, use .groupby to  create a separate dataframe aggregating by away team the variables for count, away wins, goals for and goals against. Rename the variables to denote whether they are aggregates for home team or away team.

Then merge the home and away dataframes.

Sum the values of home and away wins, games, goals for and goals against, then create the values for win percentage (wpc) and the Pythagorean expectation (pyth). 

Now repeat steps 4-6 for the 2018 games. Be sure to give different names for wpc and pyth in 2017 and 2018.

Now merge 2017 and 2018 summary files.

Now generate a correlation matrix for the wpc and pyth variables for 2017 and 2018

## Step 1

In [1]:
# Load the packages

import pandas as pd
import numpy as np
import statsmodels.formula.api as smf
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
# Load the data. 
# EPL results for the 2017/18 season

EPL18 = pd.read_excel('EPL2017-18.xlsx')
print(EPL18.columns.tolist())

FileNotFoundError: [Errno 2] No such file or directory: 'EPL2017-18.xlsx'

## Step 2

In [4]:
EPL18['home_win'] = np.where(EPL18['FTHG'] > EPL18['FTAG'], 1, 
                             np.where(EPL18['FTHG'] == EPL18['FTAG'], 0.5, 0))
EPL18['away_win'] = np.where(EPL18['FTHG'] < EPL18['FTAG'], 1, 
                             np.where(EPL18['FTHG'] == EPL18['FTAG'], 0.5, 0))
EPL18['count'] = 1

## Step 3

Create a file for games played in 2017 (before date 20180000) and another one for games played in 2018 (after date 20180000). For the 2017 games, use .groupby to create a dataframe aggregating by home team the variables for count, home wins, goals for and goals against. Then, use .groupby to create a separate dataframe aggregating by away team the variables for count, away wins, goals for and goals against. Rename the variables to denote whether they are aggregates for home team or away team.

In [5]:
EPL2017 = EPL18[ EPL18['Date'] < 20180000 ]
EPL2018 = EPL18[ EPL18['Date'] >= 20180000 ]

In [20]:
EPL2017

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,home_win,away_win,count
0,20170811,Arsenal,Leicester,4,3,H,1.0,0.0,1
1,20170812,Brighton,Man City,0,2,A,0.0,1.0,1
2,20170812,Chelsea,Burnley,2,3,A,0.0,1.0,1
3,20170812,Crystal Palace,Huddersfield,0,3,A,0.0,1.0,1
4,20170812,Everton,Stoke,1,0,H,1.0,0.0,1
5,20170812,Southampton,Swansea,0,0,D,0.5,0.5,1
6,20170812,Watford,Liverpool,3,3,D,0.5,0.5,1
7,20170812,West Brom,Bournemouth,1,0,H,1.0,0.0,1
8,20170813,Man United,West Ham,4,0,H,1.0,0.0,1
9,20170813,Newcastle,Tottenham,0,2,A,0.0,1.0,1
10,20170819,Bournemouth,Watford,0,2,A,0.0,1.0,1
11,20170819,Burnley,West Brom,0,1,A,0.0,1.0,1
12,20170819,Leicester,Brighton,2,0,H,1.0,0.0,1
13,20170819,Liverpool,Crystal Palace,1,0,H,1.0,0.0,1
14,20170819,Southampton,West Ham,3,2,H,1.0,0.0,1
15,20170819,Stoke,Arsenal,1,0,H,1.0,0.0,1
16,20170819,Swansea,Man United,0,4,A,0.0,1.0,1
17,20170820,Huddersfield,Newcastle,1,0,H,1.0,0.0,1
18,20170820,Tottenham,Chelsea,1,2,A,0.0,1.0,1
19,20170821,Man City,Everton,1,1,D,0.5,0.5,1
20,20170826,Bournemouth,Man City,1,2,A,0.0,1.0,1
21,20170826,Crystal Palace,Swansea,0,2,A,0.0,1.0,1
22,20170826,Huddersfield,Southampton,0,0,D,0.5,0.5,1
23,20170826,Man United,Leicester,2,0,H,1.0,0.0,1
24,20170826,Newcastle,West Ham,3,0,H,1.0,0.0,1
25,20170826,Watford,Brighton,0,0,D,0.5,0.5,1
26,20170827,Chelsea,Everton,2,0,H,1.0,0.0,1
27,20170827,Liverpool,Arsenal,4,0,H,1.0,0.0,1
28,20170827,Tottenham,Burnley,1,1,D,0.5,0.5,1
29,20170827,West Brom,Stoke,1,1,D,0.5,0.5,1
...,...,...,...,...,...,...,...,...,...
179,20171218,Everton,Swansea,3,1,H,1.0,0.0,1
180,20171222,Arsenal,Liverpool,3,3,D,0.5,0.5,1
181,20171223,Brighton,Watford,1,0,H,1.0,0.0,1
182,20171223,Burnley,Tottenham,0,3,A,0.0,1.0,1
183,20171223,Everton,Chelsea,0,0,D,0.5,0.5,1
184,20171223,Leicester,Man United,2,2,D,0.5,0.5,1
185,20171223,Man City,Bournemouth,4,0,H,1.0,0.0,1
186,20171223,Southampton,Huddersfield,1,1,D,0.5,0.5,1
187,20171223,Stoke,West Brom,3,1,H,1.0,0.0,1
188,20171223,Swansea,Crystal Palace,1,1,D,0.5,0.5,1
189,20171223,West Ham,Newcastle,2,3,A,0.0,1.0,1
190,20171226,Bournemouth,West Ham,3,3,D,0.5,0.5,1
191,20171226,Chelsea,Brighton,2,0,H,1.0,0.0,1
192,20171226,Huddersfield,Stoke,1,1,D,0.5,0.5,1
193,20171226,Liverpool,Swansea,5,0,H,1.0,0.0,1
194,20171226,Man United,Burnley,2,2,D,0.5,0.5,1
195,20171226,Tottenham,Southampton,5,2,H,1.0,0.0,1
196,20171226,Watford,Leicester,2,1,H,1.0,0.0,1
197,20171226,West Brom,Everton,0,0,D,0.5,0.5,1
198,20171227,Newcastle,Man City,0,1,A,0.0,1.0,1
199,20171228,Crystal Palace,Arsenal,2,3,A,0.0,1.0,1
200,20171230,Bournemouth,Everton,2,1,H,1.0,0.0,1
201,20171230,Chelsea,Stoke,5,0,H,1.0,0.0,1
202,20171230,Huddersfield,Burnley,0,0,D,0.5,0.5,1
203,20171230,Liverpool,Leicester,2,1,H,1.0,0.0,1
204,20171230,Man United,Southampton,0,0,D,0.5,0.5,1
205,20171230,Newcastle,Brighton,0,0,D,0.5,0.5,1
206,20171230,Watford,Swansea,1,2,A,0.0,1.0,1
207,20171231,Crystal Palace,Man City,0,0,D,0.5,0.5,1
208,20171231,West Brom,Arsenal,1,1,D,0.5,0.5,1

In [21]:
EPL2018

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,home_win,away_win,count
209,20180101,Brighton,Bournemouth,2,2,D,0.5,0.5,1
210,20180101,Burnley,Liverpool,1,2,A,0.0,1.0,1
211,20180101,Everton,Man United,0,2,A,0.0,1.0,1
212,20180101,Leicester,Huddersfield,3,0,H,1.0,0.0,1
213,20180101,Stoke,Newcastle,0,1,A,0.0,1.0,1
214,20180102,Man City,Watford,3,1,H,1.0,0.0,1
215,20180102,Southampton,Crystal Palace,1,2,A,0.0,1.0,1
216,20180102,Swansea,Tottenham,0,2,A,0.0,1.0,1
217,20180102,West Ham,West Brom,2,1,H,1.0,0.0,1
218,20180103,Arsenal,Chelsea,2,2,D,0.5,0.5,1
219,20180104,Tottenham,West Ham,1,1,D,0.5,0.5,1
220,20180113,Chelsea,Leicester,0,0,D,0.5,0.5,1
221,20180113,Crystal Palace,Burnley,1,0,H,1.0,0.0,1
222,20180113,Huddersfield,West Ham,1,4,A,0.0,1.0,1
223,20180113,Newcastle,Swansea,1,1,D,0.5,0.5,1
224,20180113,Tottenham,Everton,4,0,H,1.0,0.0,1
225,20180113,Watford,Southampton,2,2,D,0.5,0.5,1
226,20180113,West Brom,Brighton,2,0,H,1.0,0.0,1
227,20180114,Bournemouth,Arsenal,2,1,H,1.0,0.0,1
228,20180114,Liverpool,Man City,4,3,H,1.0,0.0,1
229,20180115,Man United,Stoke,3,0,H,1.0,0.0,1
230,20180120,Arsenal,Crystal Palace,4,1,H,1.0,0.0,1
231,20180120,Brighton,Chelsea,0,4,A,0.0,1.0,1
232,20180120,Burnley,Man United,0,1,A,0.0,1.0,1
233,20180120,Everton,West Brom,1,1,D,0.5,0.5,1
234,20180120,Leicester,Watford,2,0,H,1.0,0.0,1
235,20180120,Man City,Newcastle,3,1,H,1.0,0.0,1
236,20180120,Stoke,Huddersfield,2,0,H,1.0,0.0,1
237,20180120,West Ham,Bournemouth,1,1,D,0.5,0.5,1
238,20180121,Southampton,Tottenham,1,1,D,0.5,0.5,1
...,...,...,...,...,...,...,...,...,...
350,20180428,Swansea,Chelsea,0,1,A,0.0,1.0,1
351,20180429,Man United,Arsenal,2,1,H,1.0,0.0,1
352,20180429,West Ham,Man City,1,4,A,0.0,1.0,1
353,20180430,Tottenham,Watford,2,0,H,1.0,0.0,1
354,20180504,Brighton,Man United,1,0,H,1.0,0.0,1
355,20180505,Bournemouth,Swansea,1,0,H,1.0,0.0,1
356,20180505,Everton,Southampton,1,1,D,0.5,0.5,1
357,20180505,Leicester,West Ham,0,2,A,0.0,1.0,1
358,20180505,Stoke,Crystal Palace,1,2,A,0.0,1.0,1
359,20180505,Watford,Newcastle,2,1,H,1.0,0.0,1
360,20180505,West Brom,Tottenham,1,0,H,1.0,0.0,1
361,20180506,Arsenal,Burnley,5,0,H,1.0,0.0,1
362,20180506,Chelsea,Liverpool,1,0,H,1.0,0.0,1
363,20180506,Man City,Huddersfield,0,0,D,0.5,0.5,1
364,20180508,Swansea,Southampton,0,1,A,0.0,1.0,1
365,20180509,Chelsea,Huddersfield,1,1,D,0.5,0.5,1
366,20180509,Leicester,Arsenal,3,1,H,1.0,0.0,1
367,20180509,Man City,Brighton,3,1,H,1.0,0.0,1
368,20180509,Tottenham,Newcastle,1,0,H,1.0,0.0,1
369,20180510,West Ham,Man United,0,0,D,0.5,0.5,1
370,20180513,Burnley,Bournemouth,1,2,A,0.0,1.0,1
371,20180513,Crystal Palace,West Brom,2,0,H,1.0,0.0,1
372,20180513,Huddersfield,Arsenal,0,1,A,0.0,1.0,1
373,20180513,Liverpool,Brighton,4,0,H,1.0,0.0,1
374,20180513,Man United,Watford,1,0,H,1.0,0.0,1
375,20180513,Newcastle,Chelsea,3,0,H,1.0,0.0,1
376,20180513,Southampton,Man City,0,1,A,0.0,1.0,1
377,20180513,Swansea,Stoke,1,2,A,0.0,1.0,1
378,20180513,Tottenham,Leicester,5,4,H,1.0,0.0,1
379,20180513,West Ham,Everton,3,1,H,1.0,0.0,1

## Step 4 (home team, 2017)

In [6]:
EPL2017_home = EPL2017[['HomeTeam','FTHG','FTAG','home_win']].copy()
EPL2017_home['home_games']=1
EPL2017_home = EPL2017_home.rename(columns={'HomeTeam':'Team','FTHG':'home_R','FTAG':'home_RA','count':'home_games'})

In [7]:
EPL2017_home_by_teams = EPL2017_home.groupby('Team')['home_games','home_win','home_R','home_RA'].sum().reset_index()
EPL2017_home_by_teams

              Team  home_games  home_win  home_R  home_RA
0          Arsenal          10       8.5      25       10
1      Bournemouth          11       4.5      14       17
2         Brighton          10       5.5      10       12
3          Burnley          10       6.0       7        6
4          Chelsea          11       8.5      21        7
5   Crystal Palace          11       5.0      14       18
6          Everton          10       6.5      17       13
7     Huddersfield          11       6.0      10       12
8        Leicester          10       5.0      13       14
9        Liverpool          11       8.5      21        4
10        Man City          10       9.5      36        7
11      Man United          11       9.0      24        5
12       Newcastle          11       4.0       9       13
13     Southampton          11       5.0      13       15
14           Stoke          10       5.0      13       19
15         Swansea          10       3.0       6       15
16       Tottenham          10       7.5      21        8
17         Watford          11       4.5      14       23
18       West Brom          11       4.5      10       15
19        West Ham           9       4.0      10       14

## Step 5 (home team, 2018)

In [8]:
EPL2018_home = EPL2018[['HomeTeam','FTHG','FTAG','home_win']].copy()
EPL2018_home['home_games']=1
EPL2018_home = EPL2018_home.rename(columns={'HomeTeam':'Team','FTHG':'home_R','FTAG':'home_RA'})

In [9]:
EPL2018_home_by_teams = EPL2018_home.groupby('Team')['home_games','home_win','home_R','home_RA'].sum().reset_index()
EPL2018_home_by_teams

              Team  home_games  home_win  home_R  home_RA
0          Arsenal           9       7.5      29       10
1      Bournemouth           8       5.0      12       13
2         Brighton           9       5.5      14       13
3          Burnley           9       3.5       9       11
4          Chelsea           8       4.5       9        9
5   Crystal Palace           8       4.5      15        9
6          Everton           9       5.5      11        9
7     Huddersfield           8       2.5       6       13
8        Leicester           9       5.0      12        8
9        Liverpool           8       7.0      24        6
10        Man City           9       7.5      25        7
11      Man United           8       7.0      14        4
12       Newcastle           8       6.0      12        4
13     Southampton           8       2.5       7       11
14           Stoke           9       2.5       7       11
15         Swansea           9       4.5      11        9
16       Tottenham           9       7.5      19        8
17         Watford           8       5.5      13        8
18       West Brom           8       3.0      11       14
19        West Ham          10       6.0      14       12

## Step 6 (home team)

## Optional steps, not required for Assessment 
### (Uncomment to run)

In [ ]:
# Plot the data

#sns.relplot(x="pyth17", y="wpc17", data =EPL17)

In [ ]:
# Run the regression

#pyth_lm = smf.ols(formula = 'wpc17 ~ pyth17', data=EPL17).fit()
#pyth_lm.summary()

## Step 7 (=Step 4 (away team, 2017))

In [10]:
EPL2017_away = EPL2017[['AwayTeam','FTHG','FTAG','away_win']].copy()
EPL2017_away['away_games']=1
EPL2017_away = EPL2017_away.rename(columns={'AwayTeam':'Team','FTAG':'away_R','FTHG':'away_RA'})

In [11]:
EPL2017_away_by_teams = EPL2017_away.groupby('Team')['away_games','away_win','away_R','away_RA'].sum().reset_index()
EPL2017_away_by_teams

              Team  away_games  away_win  away_R  away_RA
0          Arsenal          11       5.0      13       16
1      Bournemouth          10       3.0       6       15
2         Brighton          11       3.0       5       13
3          Burnley          11       6.5      11       11
4          Chelsea          10       7.0      18        7
5   Crystal Palace          10       2.5       4       14
6          Everton          11       3.5       8       19
7     Huddersfield          10       3.0       8       20
8        Leicester          11       5.0      18       18
9        Liverpool          10       6.5      27       20
10        Man City          11      10.5      25        5
11      Man United          10       6.5      19       11
12       Newcastle          10       3.0      10       17
13     Southampton          10       3.0       7       15
14           Stoke          11       2.5      10       27
15         Swansea          11       3.0       7       17
16       Tottenham          10       5.5      18       12
17         Watford          10       4.5      16       14
18       West Brom          10       2.5       5       13
19        West Ham          11       3.0      12       24

## Step 7 (=Step 5 (away team, 2018))

In [12]:
EPL2018_away = EPL2018[['AwayTeam','FTHG','FTAG','away_win']].copy()
EPL2018_away['away_games']=1
EPL2018_away = EPL2018_away.rename(columns={'AwayTeam':'Team','FTAG':'away_R','FTHG':'away_RA'})
EPL2018_away_by_teams = EPL2018_away.groupby('Team')['away_games','away_win','away_R','away_RA'].sum().reset_index()
EPL2018_away_by_teams

              Team  away_games  away_win  away_R  away_RA
0          Arsenal           8       1.0       7       15
1      Bournemouth           9       4.0      13       16
2         Brighton           8       1.5       5       16
3          Burnley           8       4.0       9       11
4          Chelsea           9       4.5      14       15
5   Crystal Palace           9       4.5      12       14
6          Everton           8       2.5       8       17
7     Huddersfield           9       2.5       4       13
8        Leicester           8       2.5      13       20
9        Liverpool           9       5.0      12        8
10        Man City           8       6.5      20        8
11      Man United           9       5.5      11        8
12       Newcastle           9       3.0       8       13
13     Southampton           9       4.0      10       15
14           Stoke           8       3.0       5       11
15         Swansea           8       2.0       4       15
16       Tottenham           9       6.5      16        8
17         Watford           9       0.5       1       19
18       West Brom           9       2.5       5       14
19        West Ham           8       3.0      12       18

## Step 7 (=Step 6 (away team))

## Optional steps, not required for Assessment
### (Uncomment to run)

In [ ]:
# Plot the data

#sns.relplot(x="pyth18", y="wpc18", data =EPL2018)

In [ ]:
# Run the regression

#pyth_lm = smf.ols(formula = 'wpc18 ~ pyth18', data=EPL2018).fit()
#pyth_lm.summary()

## Step 8, 2017 Home + Away

In [13]:
EPL2017_by_team = pd.merge(EPL2017_home_by_teams,EPL2017_away_by_teams, on='Team')

EPL2017_by_team['R'] = EPL2017_by_team['home_R'] + EPL2017_by_team['away_R']
EPL2017_by_team['RA'] = EPL2017_by_team['home_RA'] + EPL2017_by_team['away_RA']
EPL2017_by_team['pyth17'] = EPL2017_by_team['R']**2 / (EPL2017_by_team['R']**2 + EPL2017_by_team['RA']**2)

EPL2017_by_team['total_wins'] = EPL2017_by_team['home_win'] + EPL2017_by_team['away_win']
EPL2017_by_team['total_games'] = EPL2017_by_team['home_games'] + EPL2017_by_team['away_games']
EPL2017_by_team['wpc17'] = EPL2017_by_team['total_wins'] / EPL2017_by_team['total_games']

EPL2017_by_team

,Team,home_games,home_win,home_R,home_RA,away_games,away_win,away_R,away_RA,R,RA,pyth17,total_wins,total_games,wpc17
0,Arsenal,10,8.5,25,10,11,5.0,13,16,38,26,0.681132,13.5,21,0.642857
1,Bournemouth,11,4.5,14,17,10,3.0,6,15,20,32,0.280899,7.5,21,0.357143
2,Brighton,10,5.5,10,12,11,3.0,5,13,15,25,0.264706,8.5,21,0.404762
3,Burnley,10,6.0,7,6,11,6.5,11,11,18,17,0.528548,12.5,21,0.595238
4,Chelsea,11,8.5,21,7,10,7.0,18,7,39,14,0.885847,15.5,21,0.738095
5,Crystal Palace,11,5.0,14,18,10,2.5,4,14,18,32,0.240356,7.5,21,0.357143
6,Everton,10,6.5,17,13,11,3.5,8,19,25,32,0.379018,10.0,21,0.476190
7,Huddersfield,11,6.0,10,12,10,3.0,8,20,18,32,0.240356,9.0,21,0.428571
8,Leicester,10,5.0,13,14,11,5.0,18,18,31,32,0.484131,10.0,21,0.476190
9,Liverpool,11,8.5,21,4,10,6.5,27,20,48,24,0.800000,15.0,21,0.714286
10,Man City,10,9.5,36,7,11,10.5,25,5,61,12,0.962743,20.0,21,0.952381
11,Man United,11,9.0,24,5,10,6.5,19,11,43,16,0.878385,15.5,21,0.738095
12,Newcastle,11,4.0,9,13,10,3.0,10,17,19,30,0.286281,7.0,21,0.333333
13,Southampton,11,5.0,13,15,10,3.0,7,15,20,30,0.307692,8.0,21,0.380952
14,Stoke,10,5.0,13,19,11,2.5,10,27,23,46,0.200000,7.5,21,0.357143
15,Swansea,10,3.0,6,15,11,3.0,7,17,13,32,0.141660,6.0,21,0.285714
16,Tottenham,10,7.5,21,8,10,5.5,18,12,39,20,0.791775,13.0,20,0.650000
17,Watford,11,4.5,14,23,10,4.5,16,14,30,37,0.396651,9.0,21,0.428571
18,West Brom,11,4.5,10,15,10,2.5,5,13,15,28,0.222993,7.0,21,0.333333
19,West Ham,9,4.0,10,14,11,3.0,12,24,22,38,0.251037,7.0,20,0.350000

In [32]:
EPL2017_by_team['diff'] = EPL2017_by_team['pyth17'] - EPL2017_by_team['wpc17']
EPL2017_by_team.sort_values(by='away_win')

,Team,home_games,home_win,home_R,home_RA,away_games,away_win,away_R,away_RA,R,RA,pyth17,total_wins,total_games,wpc17,diff
5,Crystal Palace,11,5.0,14,18,10,2.5,4,14,18,32,0.240356,7.5,21,0.357143,-0.116787
14,Stoke,10,5.0,13,19,11,2.5,10,27,23,46,0.200000,7.5,21,0.357143,-0.157143
18,West Brom,11,4.5,10,15,10,2.5,5,13,15,28,0.222993,7.0,21,0.333333,-0.110340
19,West Ham,9,4.0,10,14,11,3.0,12,24,22,38,0.251037,7.0,20,0.350000,-0.098963
1,Bournemouth,11,4.5,14,17,10,3.0,6,15,20,32,0.280899,7.5,21,0.357143,-0.076244
2,Brighton,10,5.5,10,12,11,3.0,5,13,15,25,0.264706,8.5,21,0.404762,-0.140056
15,Swansea,10,3.0,6,15,11,3.0,7,17,13,32,0.141660,6.0,21,0.285714,-0.144055
7,Huddersfield,11,6.0,10,12,10,3.0,8,20,18,32,0.240356,9.0,21,0.428571,-0.188215
13,Southampton,11,5.0,13,15,10,3.0,7,15,20,30,0.307692,8.0,21,0.380952,-0.073260
12,Newcastle,11,4.0,9,13,10,3.0,10,17,19,30,0.286281,7.0,21,0.333333,-0.047053
6,Everton,10,6.5,17,13,11,3.5,8,19,25,32,0.379018,10.0,21,0.476190,-0.097173
17,Watford,11,4.5,14,23,10,4.5,16,14,30,37,0.396651,9.0,21,0.428571,-0.031921
0,Arsenal,10,8.5,25,10,11,5.0,13,16,38,26,0.681132,13.5,21,0.642857,0.038275
8,Leicester,10,5.0,13,14,11,5.0,18,18,31,32,0.484131,10.0,21,0.476190,0.007941
16,Tottenham,10,7.5,21,8,10,5.5,18,12,39,20,0.791775,13.0,20,0.650000,0.141775
3,Burnley,10,6.0,7,6,11,6.5,11,11,18,17,0.528548,12.5,21,0.595238,-0.066690
11,Man United,11,9.0,24,5,10,6.5,19,11,43,16,0.878385,15.5,21,0.738095,0.140290
9,Liverpool,11,8.5,21,4,10,6.5,27,20,48,24,0.800000,15.0,21,0.714286,0.085714
4,Chelsea,11,8.5,21,7,10,7.0,18,7,39,14,0.885847,15.5,21,0.738095,0.147752
10,Man City,10,9.5,36,7,11,10.5,25,5,61,12,0.962743,20.0,21,0.952381,0.010362

## Step 9, 2018 Home + Away

In [15]:
EPL2018_by_team = pd.merge(EPL2018_home_by_teams,EPL2018_away_by_teams, on='Team')
EPL2018_by_team['R'] = EPL2018_by_team['home_R'] + EPL2018_by_team['away_R']
EPL2018_by_team['RA'] = EPL2018_by_team['home_RA'] + EPL2018_by_team['away_RA']
EPL2018_by_team['pyth18'] = EPL2018_by_team['R']**2 / (EPL2018_by_team['R']**2 + EPL2018_by_team['RA']**2)

EPL2018_by_team['total_wins'] = EPL2018_by_team['home_win'] + EPL2018_by_team['away_win']
EPL2018_by_team['total_games'] = EPL2018_by_team['home_games'] + EPL2018_by_team['away_games']
EPL2018_by_team['wpc18'] = EPL2018_by_team['total_wins'] / EPL2018_by_team['total_games']

EPL2018_by_team

,Team,home_games,home_win,home_R,home_RA,away_games,away_win,away_R,away_RA,R,RA,pyth18,total_wins,total_games,wpc18
0,Arsenal,9,7.5,29,10,8,1.0,7,15,36,25,0.674649,8.5,17,0.500000
1,Bournemouth,8,5.0,12,13,9,4.0,13,16,25,29,0.426330,9.0,17,0.529412
2,Brighton,9,5.5,14,13,8,1.5,5,16,19,29,0.300333,7.0,17,0.411765
3,Burnley,9,3.5,9,11,8,4.0,9,11,18,22,0.400990,7.5,17,0.441176
4,Chelsea,8,4.5,9,9,9,4.5,14,15,23,24,0.478733,9.0,17,0.529412
5,Crystal Palace,8,4.5,15,9,9,4.5,12,14,27,23,0.579491,9.0,17,0.529412
6,Everton,9,5.5,11,9,8,2.5,8,17,19,26,0.348120,8.0,17,0.470588
7,Huddersfield,8,2.5,6,13,9,2.5,4,13,10,26,0.128866,5.0,17,0.294118
8,Leicester,9,5.0,12,8,8,2.5,13,20,25,28,0.443577,7.5,17,0.441176
9,Liverpool,8,7.0,24,6,9,5.0,12,8,36,14,0.868633,12.0,17,0.705882
10,Man City,9,7.5,25,7,8,6.5,20,8,45,15,0.900000,14.0,17,0.823529
11,Man United,8,7.0,14,4,9,5.5,11,8,25,12,0.812744,12.5,17,0.735294
12,Newcastle,8,6.0,12,4,9,3.0,8,13,20,17,0.580552,9.0,17,0.529412
13,Southampton,8,2.5,7,11,9,4.0,10,15,17,26,0.299482,6.5,17,0.382353
14,Stoke,9,2.5,7,11,8,3.0,5,11,12,22,0.229299,5.5,17,0.323529
15,Swansea,9,4.5,11,9,8,2.0,4,15,15,24,0.280899,6.5,17,0.382353
16,Tottenham,9,7.5,19,8,9,6.5,16,8,35,16,0.827144,14.0,18,0.777778
17,Watford,8,5.5,13,8,9,0.5,1,19,14,27,0.211892,6.0,17,0.352941
18,West Brom,8,3.0,11,14,9,2.5,5,14,16,28,0.246154,5.5,17,0.323529
19,West Ham,10,6.0,14,12,8,3.0,12,18,26,30,0.428934,9.0,18,0.500000

In [27]:
EPL2018_by_team['diff'] = EPL2018_by_team['pyth18'] - EPL2018_by_team['wpc18']
EPL2018_by_team.sort_values(by='diff')

,Team,home_games,home_win,home_R,home_RA,away_games,away_win,away_R,away_RA,R,RA,pyth18,total_wins,total_games,wpc18,diff
7,Huddersfield,8,2.5,6,13,9,2.5,4,13,10,26,0.128866,5.0,17,0.294118,-0.165252
17,Watford,8,5.5,13,8,9,0.5,1,19,14,27,0.211892,6.0,17,0.352941,-0.141049
6,Everton,9,5.5,11,9,8,2.5,8,17,19,26,0.348120,8.0,17,0.470588,-0.122469
2,Brighton,9,5.5,14,13,8,1.5,5,16,19,29,0.300333,7.0,17,0.411765,-0.111432
1,Bournemouth,8,5.0,12,13,9,4.0,13,16,25,29,0.426330,9.0,17,0.529412,-0.103082
15,Swansea,9,4.5,11,9,8,2.0,4,15,15,24,0.280899,6.5,17,0.382353,-0.101454
14,Stoke,9,2.5,7,11,8,3.0,5,11,12,22,0.229299,5.5,17,0.323529,-0.094230
13,Southampton,8,2.5,7,11,9,4.0,10,15,17,26,0.299482,6.5,17,0.382353,-0.082871
18,West Brom,8,3.0,11,14,9,2.5,5,14,16,28,0.246154,5.5,17,0.323529,-0.077376
19,West Ham,10,6.0,14,12,8,3.0,12,18,26,30,0.428934,9.0,18,0.500000,-0.071066
4,Chelsea,8,4.5,9,9,9,4.5,14,15,23,24,0.478733,9.0,17,0.529412,-0.050679
3,Burnley,9,3.5,9,11,8,4.0,9,11,18,22,0.400990,7.5,17,0.441176,-0.040186
8,Leicester,9,5.0,12,8,8,2.5,13,20,25,28,0.443577,7.5,17,0.441176,0.002401
16,Tottenham,9,7.5,19,8,9,6.5,16,8,35,16,0.827144,14.0,18,0.777778,0.049366
5,Crystal Palace,8,4.5,15,9,9,4.5,12,14,27,23,0.579491,9.0,17,0.529412,0.050079
12,Newcastle,8,6.0,12,4,9,3.0,8,13,20,17,0.580552,9.0,17,0.529412,0.051140
10,Man City,9,7.5,25,7,8,6.5,20,8,45,15,0.900000,14.0,17,0.823529,0.076471
11,Man United,8,7.0,14,4,9,5.5,11,8,25,12,0.812744,12.5,17,0.735294,0.077450
9,Liverpool,8,7.0,24,6,9,5.0,12,8,36,14,0.868633,12.0,17,0.705882,0.162750
0,Arsenal,9,7.5,29,10,8,1.0,7,15,36,25,0.674649,8.5,17,0.500000,0.174649

In [28]:
EPL2018_by_team['diff_home_vs_away'] = EPL2018_by_team['home_win'] - EPL2018_by_team['away_win']
EPL2018_by_team.sort_values(by='diff_home_vs_away')

,Team,home_games,home_win,home_R,home_RA,away_games,away_win,away_R,away_RA,R,RA,pyth18,total_wins,total_games,wpc18,diff,diff_home_vs_away
13,Southampton,8,2.5,7,11,9,4.0,10,15,17,26,0.299482,6.5,17,0.382353,-0.082871,-1.5
3,Burnley,9,3.5,9,11,8,4.0,9,11,18,22,0.400990,7.5,17,0.441176,-0.040186,-0.5
14,Stoke,9,2.5,7,11,8,3.0,5,11,12,22,0.229299,5.5,17,0.323529,-0.094230,-0.5
4,Chelsea,8,4.5,9,9,9,4.5,14,15,23,24,0.478733,9.0,17,0.529412,-0.050679,0.0
5,Crystal Palace,8,4.5,15,9,9,4.5,12,14,27,23,0.579491,9.0,17,0.529412,0.050079,0.0
7,Huddersfield,8,2.5,6,13,9,2.5,4,13,10,26,0.128866,5.0,17,0.294118,-0.165252,0.0
18,West Brom,8,3.0,11,14,9,2.5,5,14,16,28,0.246154,5.5,17,0.323529,-0.077376,0.5
1,Bournemouth,8,5.0,12,13,9,4.0,13,16,25,29,0.426330,9.0,17,0.529412,-0.103082,1.0
16,Tottenham,9,7.5,19,8,9,6.5,16,8,35,16,0.827144,14.0,18,0.777778,0.049366,1.0
10,Man City,9,7.5,25,7,8,6.5,20,8,45,15,0.900000,14.0,17,0.823529,0.076471,1.0
11,Man United,8,7.0,14,4,9,5.5,11,8,25,12,0.812744,12.5,17,0.735294,0.077450,1.5
9,Liverpool,8,7.0,24,6,9,5.0,12,8,36,14,0.868633,12.0,17,0.705882,0.162750,2.0
15,Swansea,9,4.5,11,9,8,2.0,4,15,15,24,0.280899,6.5,17,0.382353,-0.101454,2.5
8,Leicester,9,5.0,12,8,8,2.5,13,20,25,28,0.443577,7.5,17,0.441176,0.002401,2.5
19,West Ham,10,6.0,14,12,8,3.0,12,18,26,30,0.428934,9.0,18,0.500000,-0.071066,3.0
6,Everton,9,5.5,11,9,8,2.5,8,17,19,26,0.348120,8.0,17,0.470588,-0.122469,3.0
12,Newcastle,8,6.0,12,4,9,3.0,8,13,20,17,0.580552,9.0,17,0.529412,0.051140,3.0
2,Brighton,9,5.5,14,13,8,1.5,5,16,19,29,0.300333,7.0,17,0.411765,-0.111432,4.0
17,Watford,8,5.5,13,8,9,0.5,1,19,14,27,0.211892,6.0,17,0.352941,-0.141049,5.0
0,Arsenal,9,7.5,29,10,8,1.0,7,15,36,25,0.674649,8.5,17,0.500000,0.174649,6.5

Merge 2017, 2018

In [19]:
EPL_1718 = pd.merge(EPL2017_by_team,EPL2018_by_team, on='Team')

keyvars = EPL_1718[['Team','wpc17','wpc18','pyth17','pyth18']]
keyvars.corr()

           wpc17     wpc18    pyth17    pyth18
wpc17   1.000000  0.756573  0.968204  0.745832
wpc18   0.756573  1.000000  0.795693  0.955986
pyth17  0.968204  0.795693  1.000000  0.795331
pyth18  0.745832  0.955986  0.795331  1.000000

## Optional steps, not required for Assessment
### (Uncomment to run)

In [ ]:
#sns.relplot(x="pyth17", y="wpc18", data =Half2predictor)

In [ ]:
#sns.relplot(x="wpc17", y="wpc18", data =Half2predictor)

Now you have completed the assignment, are these results consistent with those we found for Major League Baseball?